apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-controller
spec:
  replicas: 2
  selector:
    app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: k8s-demo
        # image: wardviaene/k8s-demo
        image: ypd04208625/express-test
        # image: express-test
        ports:
        - name: nodejs-port
          containerPort: 3000
